spring.application.name=USER-SERVICE

server.port=8084

# SQL Server datasource - same style as Quiz/Question services
spring.datasource.url=jdbc:sqlserver://VIRUS\\TESTINSTANCE;databaseName=userdb;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Vicky@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# JWT - this SAME secret key must be copied into ApiGateway's application.properties
jwt.secretKey=dh3jrh3ruweijfwerq8rq0e9uqwjwqicqehyr893rnc89urc3nu39ecn39cunw
jwt.expirationMs=86400000

# Auto-seeded admin (created once on startup if no ADMIN exists yet)
admin.default.username=admin
admin.default.password=Admin@123
